version: "3.7"
services:

  database:
    build: data/.
    volumes:
      - ./data:/usr/share/nginx/html
    restart: always
    ports:
      - "3000:80"

  web:
    # replace username/repo:tag with your name and image details
    build:
      context: .
      target:  dev-stage
    volumes:
      - ./:/usr/share/nginx/html
    ports:
      - "8080:80"
    links:
      - database
    command: npm run dev
