version: "3.7"
services:

  database:
    build: data/.
    volumes:
      - ./data:/usr/share/nginx/html
    restart: always
    ports:
      - "3000:80"

  web:
    build:
      context: ./
      target:  dev-stage
    volumes:
      - ./:/usr/share/nginx/html
      - ./:/bindmount:rw
      - node_modules:/src/node_modules
    ports:
      - "8080:8080"
    links:
      - database
    command: npm run dev

volumes:
  node_modules:
